#! /bin/sh

dd if=test-old of=test-mbr 2>/dev/null
do_install -f /dev/zero -l -e+ >test-y
cat <<EOF >test-x
Version: 2
Compatible: 2
Y2K-Fix: Disabled
Drive: 0x80
Default: D
Timeout: 18/18 seconds
Enabled: F A
Interrupt: Shift Key
EOF
diff -u test-x test-y

: Done
