#! /bin/sh
# Check long delays, boots floppy.
cat <<EOF >test-x
Version: 2
Compatible: 2
Y2K-Fix: Disabled
Drive: 0x80
Default: 1
Timeout: 520/18 seconds
Enabled: F A
Interrupt: Key
EOF
do_install -l -r -d 0x80 -ik -t 520 -p 1 -eaf test-mbr >test-y
diff -u test-x test-y
cat <<EOF >test-x
Output: "\rMBR "
Time: 275
Event list empty.
Output: "\rMBR 2FA"
Time: 276
Output: ":\r\rMBR "
Read sector d0 h0 c0 s1 to 0000:7c00
Output: "\r"
Time: 277
Output: "\n"
Exit: 0000 0000 0000 0001
Floppy boot.
eax:00000e0a ebx:00000000 ecx:00000001 edx:00000000 PC:0000:00007c02
esi:00000790 edi:00000005 ebp:00000000 efl:00030246 SP:0000:00000000
ds:0000 es:0000 fs:0000 gs:0000 FLAGS: c P a Z s t I d o
EOF
harness test-mbr -r10 -w275 -k 0x2166 >test-y
diff -u test-x test-y

: Done
